server:
  port: 8000
  servlet:
    context-path: /chat
websocket:
  port: 8999
  max_port: 9999

spring:
  application:
    name: one-form

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.16.1.246:13306/im_server?useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: hz310012
    hikari:
      # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 10
      # 最小空闲连接，默认值 10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 2
      # 连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      # 空闲连接超时时间，默认值600000ms（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；
      # 不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放(自动释放过期链接)
      idle-timeout: 600000
      # 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 640000
      # 连接测试查询
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0

knife4j:
  enable: true